### ISSUE TITLE
Xcode14.2 Fatal error: The operation couldn’t be completed. (SwiftSyntaxParser.ParserError error 1.)

### ISSUE THREAD

**Issue by kabirkhaan** [uber/mockolo#219] opened 2023-03-07 15:44 UTC
After updating Mockolo version 1.8.1, we are facing a folloiwing issue.

> MockoloFramework/SourceParser.swift:105: Fatal error: The operation couldn’t be completed. (SwiftSyntaxParser.ParserError error 1.)

Till Mocolo version 1.7.1 every things works fine.

Seems like it related swift-syntax version.
https://github.com/uber/mockolo/blob/2b425df144b0a1e61bf2202d481637741b2b3270/Package.swift#L18

ENVIRONMENT
- ARM64 M1

How the Mockolo is integated in project?
- Extracting the [mockolo.tar.gz](https://github.com/uber/mockolo/releases/download/1.8.1/mockolo.tar.gz)

Other Context
- We tried it with `1.8.0` it's also not working, aslo figure out that mockolo Version file is not update with which is fixed in v1.8.1
- Fetching the ` 1.8.1` via [MINT](https://github.com/yonaskolb/Mint) works

**Comment by sidepelican** [comment] 2023-03-13 08:37
This was also reproduced in my environment.

The cause of this issue is the steps of building `mockolo.tar.gz`.
This tar file is build by GitHub Actions.
https://github.com/uber/mockolo/blob/2b425df144b0a1e61bf2202d481637741b2b3270/.github/workflows/release.yml#L16

In `/install-script.sh`, it copies libISSP in Xcode ToolChain. This is wrong now. It should be used the libISSP resolved by SwiftPM (it will be placed in the `.build/release` folder.)
https://github.com/uber/mockolo/blob/2b425df144b0a1e61bf2202d481637741b2b3270/install-script.sh#L72

**Closed** 2023-03-15 11:21 UTC
